/* tslint:disable */
 

/* auto-generated by NAPI-RS */

/** Configuration for file search initialization */
export interface SearchConfig {
  projectRoot: string;
  useGitignore: boolean;
  useQwenignore: boolean;
  ignoreDirs: Array<string>;
  enableFuzzySearch: boolean;
  maxDepth?: number;
}
/** Search result item */
export interface SearchResult {
  path: string;
  score?: number;
}
/** Main file search class - wraps the Rust implementation */
export declare class FileSearch {
  /** Create a new FileSearch instance */
  constructor(config: SearchConfig);
  /** Initialize the search engine by crawling the filesystem */
  initialize(): Promise<void>;
  /** Search for files matching a pattern */
  search(
    pattern: string,
    maxResults?: number | undefined | null,
  ): Promise<Array<SearchResult>>;
  /** Get all crawled files (for debugging/testing) */
  getAllFiles(): Array<string>;
}
